### ISSUE TITLE
Auto Grading

### ISSUE THREAD

**Issue by nixpulvis** [nixpulvis/bottlenose#6]
Extending the existing Makefile based auto grading system. This should be able to fill in the `auto_score` field of a submission.

**Comment by nixpulvis** [comment]
Ben gave me the following example script.

```
ROOTDIR=<root of the grading filesystem>
TIMEOUT=120s
student=$1
pset=$2
testclass="Grade{$pset/-/}"
graderdir=<directory where to find testclasses>
psetdir=<directory where to find skeleton code>
asstdir="$ROOTDIR"/"$student"/assignments/"$pset"
filesdir="$asstdir"/files
builddir="$asstdir"/build
profdir="$asstdir"/prof-eval
outfile="$filesdir"/grader.out

# Nuke any old build directory
rm -rf "$builddir"
mkdir -p "$builddir"
rm -rf "$outfile"

# Copy instructor files
find "$psetdir" -name \*.java -exec cp {} "$builddir" \;

# Copy student files
cp -R "$filesdir"/* "$builddir"

# Copy testing files
cp $graderdir/GradingSandbox.java "$builddir"
cp $graderdir/$testclass.java "$builddir"

# Grade!
cd $builddir
CLASSPATH=".:$CLASSPATH"
find . -mindepth 2 -name \*.java | xargs javac -Xlint:unchecked -Xlint:deprecation > $outfile
timeout -k "$TIMEOUT" "$TIMEOUT" java -cp $CLASSPATH org.junit.runner.JUnitCode $testclass >> $outfile
<do something to get the grade from $outfile into $profdir>
```

**Comment by blerner** [comment]
Additional things you can run: For Fundies 2, the autograding is something like `java -cp tester.jar tester.Main StudentExamplesClassName`, assuming you've `javac`'ed all the submitted files already.  I don't have a script or Makefile for that handy, since it's built into WebCAT, but it should be trivial to throw together.

Note that when building the compilation script for Fundies 2, we may want the ability to specify command-line options to javac, like `-Xlint:unchecked` or not, depending on the assignment.  I don't know precisely what the command is that WebCAT runs (it doesn't produce a transcript anywhere of what commands are run), so there will have to be some experimentation...

The tester library produces output that looks like this:
```
------------- ExamplesExcelCellsReference: standard output ---------------


-----------------------------------
Tests for the class: ExamplesExcelCellsReference
Tester Prima v.1.5.1 - 17 June 2012
-----------------------------------
Tests defined in the class: ExamplesExcelCellsReference:
---------------------------

Ran 7 tests.
1 test failed.

Failed test results: 
--------------

Error in test number 7
An exception occurred while executing the method testStudentData()

java.lang.NullPointerException
        at Formula.value(ExcelCells.java:113)
        at Cell.value(ExcelCells.java:32)
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:14)

--- END OF TEST RESULTS ---
------------- ---------------- ---------------
```
or
```
------------- ExamplesExcelCellsReference: standard output ---------------


-----------------------------------
Tests for the class: ExamplesExcelCellsReference
Tester Prima v.1.5.1 - 17 June 2012
-----------------------------------
Tests defined in the class: ExamplesExcelCellsReference:
---------------------------

Ran 32 tests.
13 tests failed.

Failed test results: 
--------------

Error in test number 16
formula(0) of A5
actual:                                 expected:
 "Its somthing"................................... "A5"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:23)

Error in test number 17
formula(1) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(D3, C5)"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:24)

Error in test number 18
formula(2) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(D2, A1), sub(D4, B3))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:25)

Error in test number 19
formula(3) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(mod(B2, E2), 13), sub(sub(C4, A1), mod(E1, A3)))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:26)

Error in test number 20
formula(4) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(mod(sub(A3, C1), sub(E1, D1)), 13), sub(sub(mul(E1, D1), 13), mod(7, mul(A1, B1))))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:27)

Error in test number 21
formula(5) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(mod(sub(mul(A1, B1), 2), sub(7, 3)), 13), sub(sub(mul(7, 3), 13), mod(7, mul(13, 5))))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:28)

Error in test number 22
formula(6) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(mod(sub(mul(13, 5), 2), sub(7, 3)), 13), sub(sub(mul(7, 3), 13), mod(7, mul(13, 5))))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:29)

Error in test number 23
formula(15) of A5
actual:                                 expected:
 "Its somthing"................................... "mod(mul(mod(sub(mul(13, 5), 2), sub(7, 3)), 13), sub(sub(mul(7, 3), 13), mod(7, mul(13, 5))))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:30)

Error in test number 24
formula(0) of D2
actual:                                 expected:
 "Its somthing"................................... "D2"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:31)

Error in test number 25
formula(1) of D2
actual:                                 expected:
 "Its somthing"................................... "mod(B2, E2)"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:32)

Error in test number 26
formula(2) of D2
actual:                                 expected:
 "Its somthing"................................... "mod(sub(A3, C1), sub(E1, D1))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:33)

Error in test number 27
formula(3) of D2
actual:                                 expected:
 "Its somthing"................................... "mod(sub(mul(A1, B1), 2), sub(7, 3))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:34)

Error in test number 28
formula(4) of D2
actual:                                 expected:
 "Its somthing"................................... "mod(sub(mul(13, 5), 2), sub(7, 3))"


tester.ErrorReport: Error trace:
        at ExamplesExcelCellsReference.testStudentData(hw02_p2_tests.java:35)

--- END OF TEST RESULTS ---
------------- ---------------- ---------------
```
The relevant bits are: "Ran M tests. N tests failed.", which gives a autograder score of (100% - N/M), and "Error in test number ###".  We'll need to split the output at each of those lines, to get chunks of text for each failed test, and then show at most a few of them (could be hardcoded to 3, but preferably a configurable number) as hints to students.  NOTE: The output **must** be shown in `fixed-width` font with `<pre>` whitespace, or else it'll become illegible...  Most test outputs are multiple lines long (these are from an early homework, so they're very short), and line wrapping is awful here.

**Comment by nixpulvis** [comment]
So the way I see it right now a submission has many different grades, each of a "kind" in the case of these auto grading scripts the kind would be some script, which tells the systems what to do to fill in the grade. In the case of a manual grade the kind might be simple "staff" and it would be filled in by hand. Grades are pre-populated for each submission based on the assignment, with `null` grade values by default.

@blerner does this sound sensible to you?

**Comment by blerner** [comment]
Yes, but you're leaving out several other important features, like the per-line or per-assignment notes that human-graders make, or the autograder output above.  Each grader is more than just a *score*.

**Comment by nixpulvis** [comment]
Yea, what do you think about a grade being a non-null score, and an optional set of notes.
